title: Nighthawk Pages
description: "Class of 2025"
owner_name: Yusuf Khan
github_username: YusufK-25
github_repo: "yusuf_2025"
baseurl: "/yusuf_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark 
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0

plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/tool1.md
  - navigation/calculator.md
  - navigation/rpg3x.md
  - README4YML.md